### ISSUE TITLE
Sync only new issues and remove dependency on hardcoded issue count with wget mirror

### ISSUE THREAD

**Issue by Gadgetoid** [joergi/MagPiDownloader#1]
First off; great idea! Now you've got me wondering if I can run this directly on my hacked E-reader.

Forgive me if there's a reason I've missed for your method, but wget actually has some super powerful features for accomplishing this.

Here's an example for English MagPi issues using the long-winded wget option names so you can see what's going on:

```
wget --recursive --no-directories --no-parent https://www.raspberrypi.org/magpi-issues/ --directory-prefix issues --mirror --accept-regex "/MagPi[0-9]+\.pdf"
```

This will download all issues in the format `MagPi00.pdf` into the `issues` folder. It will skip an issue if it's already downloaded.

**Comment by Gadgetoid** [comment]
Looks like `index.html` and `robots.txt` end up in `issues` too, which is messy, so I'd use:

```
#!/bin/bash

wget https://www.raspberrypi.org/magpi-issues/ \
--recursive \
--no-directories \
--no-parent \
--directory-prefix issues \
--mirror \
--accept-regex "/MagPi[0-9]+\.pdf" \
--reject index.html \
--execute robots=off
```

**Comment by joergi** [comment]
Hell yeah, you made the first issue on this small project, thx :1st_place_medal: 

I 'll have a look for, latest in the next week!

**Comment by joergi** [comment]
Thanks for your help, I used this now in the main script!
