### ISSUE TITLE
Invoke-WebRequest not found

### ISSUE THREAD

**Issue by jaspercayne** [joergi/MagPiDownloader#14]
Anyone that is using an older version of powershell will not be able to run the scripts by default because Invoke-WebRequest was not available before PowerShell v3.0.

One needs to update PowerShell to at least v3 in order to use this repository in the default state, or changes need to be made to the ps1 scripts to allow it to be backward compatible with PowerShell < v3.0.

The exact error that is thrown is below:
```
The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\Git\MagPiDownloader\windows\magpi-issue-downloader.ps1:34 char:28
+     $l = (Invoke-WebRequest <<<<  -Uri $baseUrl -usebasicparsing).Links
    + CategoryInfo          : ObjectNotFound: (Invoke-WebRequest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Rubemlrm** [comment]
thanks for the report @jaspercayne i will try fix that in the following days =)

**Comment by joergi** [comment]
thanks for your input @jaspercayne!

**Comment by joergi** [comment]
@Rubemlrm  any info on this?
and, honestly: do we need older versions of the powershell? I have no idea about since when ps3 is used....

**Comment by Rubemlrm** [comment]
@joergi for what i've checked the ps3 was released in 2012, i don't know if you want to give support to such legacy version. There at least 2 major versions above and microsoft is promoting the powershell core version to use.

**Comment by joergi** [comment]
@Rubemlrm as I'm not on windows at all, I don't really care. it's totally up to you, if you wanna do it or not...
@jaspercayne - do you think it's needed?

**Comment by joergi** [comment]
Closed because no reply by the author @jaspercayne
