### ISSUE TITLE
URLs for downloads have changed, scripts no longer work

### ISSUE THREAD

**Issue by Jakethethird** [joergi/MagPiDownloader#15]
For issue 89 for example:

https://magpi.raspberrypi.org/issues/89/pdf

Thus, the scripts need updating.

Jake

**Comment by joergi** [comment]
Thanks a lot Jake, 
I will have a look in the next days...

**Comment by joergi** [comment]
@Rubemlrm  -  the Merge was too early. tests were green, but still not working, can you revert it?

**Comment by Rubemlrm** [comment]
@joergi  sorry :/ that looked fine, because of that i've merged

**Comment by joergi** [comment]
@Rubemlrm no problem. it will work now for more issues, but the last 3 or 4 are not working yet.

I just made a new PR where the tests should fail now ;-)

**Comment by joergi** [comment]
I got a response from The MagPi 
"Hey Jorgi, sorry for the slow response, had to check with our web team. Unfortunately, the numbers are a bit random so no way to translate that - however, they are automatically redirected from the links on the site such as: https://magpi.raspberrypi.org/issues/80/pdf

Don't know if that will help you but that's the best we can do for now. Sorry!"

I'm trying at the moment to follow the redirect with wget or curl
but not working yet.... :-(   any help is welcome

**Comment by joergi** [comment]
one solution provided by _this account has been_ on [stackexchante](https://unix.stackexchange.com/questions/564395/wget-curl-is-not-following-the-redirect-of-my-url?noredirect=1#comment1049446_564395) would be 
`curl -fsS "https://magpi.raspberrypi.org/issues/89/pdf" | awk -v 'RS=<' -F\> '/^meta http-equiv="refresh"/ && $1 ~ /url=/{split($1,a,"[?=\"]");exit} END{print "url=\""a[7]"\""}' | curl -f --remote-name-all -K-`

**Comment by keni-n** [comment]
My suggestion is
`curl -fs "https://magpi.raspberrypi.org/issues/89/pdf" | grep c-link | sed
's/^.*href=\"//' | sed 's/\?.*$//'`

**Comment by joergi** [comment]
thx, will try it these days.

**Comment by joergi** [comment]
The fix from @keni-n worked for the Linux version, but it's not working for Windows yet, as you can see here in this PR:  #17 
@Rubemlrm - do you have any idea, how to get the changes from @keni-n in his PR #19 into the Windows ?

**Comment by Rubemlrm** [comment]
@joergi i will try to give a check for that solution, to see if i can do something with the powershell version.

**Comment by Rubemlrm** [comment]
@joergi for what i've check looks that i need to refactor the script to handle with the parse of html response from magpi request. Powershell have some methods that can help with that. Let me see if in the following days i can fix this.

**Comment by keni-n** [comment]
FYI: @joergi If you are interested in HackSpace Magazine, you can adapt the code by modifying it.

```
-               printf -v page_url "https://magpi.raspberrypi.org/issues/%02d/pdf" $i
-               pdf_url=`curl -sf $page_url | grep c-link | sed 's/^.*href=\"//' | sed 's/\?.*$//'`
+               printf -v page_url "https://hackspace.raspberrypi.org/issues/%02d/pdf" $i
+               pdf_url=`curl -sf $page_url | grep \"c-link\" | sed 's/^.*href=\"//' | sed 's/\?.*$//'`
```

**Comment by joergi** [comment]
@keni-n - there is a Hackspace project, haven't looked at it for a longer time:
https://github.com/joergi/Hackspace-Magazine-Downloader/

feel free to make a PR, the fame should be on your side ;-)
