### ISSUE TITLE
[Windows] - Powershell script should use issues.txt too

### ISSUE THREAD

**Issue by joergi** [joergi/MagPiDownloader#20]
The Windows [powershell script should also use](https://github.com/joergi/MagPiDownloader/blob/master/windows/magpi-issue-downloader.ps1#L21) the [issues.txt](https://github.com/joergi/MagPiDownloader/blob/master/issues.txt) file as the Linux one.

**Comment by joergi** [comment]
@Rubemlrm - if you have any idea how to it, feel free.
I will copy the solution later also to [this issue too](https://github.com/joergi/Hackspace-Magazine-Downloader/issues/2) if you don't wanna do it ;-)

**Comment by Rubemlrm** [comment]
I think that I can get the value directly from file :), need to test that.
