### ISSUE TITLE
Special issues: please resolve, with powershell in windows 11

### ISSUE THREAD

**Issue by DEMG-DEV** [joergi/MagPiDownloader#240]
when i was using the follow file ```magpi-special-issue-downloader.ps1``` i got the error

![image](https://github.com/user-attachments/assets/7bffdac9-e192-4f7e-9fdd-c07cca1eda19)

i resolved changing ```pwsh``` to ```powershell```

![image](https://github.com/user-attachments/assets/697c2608-93f6-486a-b99a-9fa3fe7e353f)

**Comment by joergi** [comment]
If I was reading correct, pwsh should be installed on any Windows. powershell is something different right?

From chatgpt:
When to use which:

    Use pwsh if:
        You have PowerShell Core installed (version 6 or later).
        You need cross-platform compatibility.
        You're leveraging modern PowerShell features.
    Use powershell if:
        You're working with scripts that rely on Windows-specific features or older cmdlets.
        You haven't installed PowerShell Core and want to use the built-in Windows PowerShell (version 5.1).
        
so, I will still use pwsh and not powershell.
maybe something odd with your system?
the tests also work with `pwsh`

please let me know if I understand something wrong @DEMG-DEV

**Comment by Jaykul** [comment]
(Windows) `powershell` is the old one that's still built in on Windows. 
`pwsh` is the current, cross-platform version.

**Comment by joergi** [comment]
THX @Jaykul  for explaining it.
