### ISSUE TITLE
test the dockerized build

### ISSUE THREAD

**Issue by joergi** [joergi/MagPiDownloader#26]
test the dockerized build

**Comment by Rubemlrm** [comment]
Maybe this can be helpfull https://github.com/actions/starter-workflows/blob/master/ci/docker-publish.yml

**Comment by FaithKovi** [comment]
Hello, @joergi  I will like to contribute to this project.

**Comment by joergi** [comment]
Feel free, help is always welcomed, as my time is a little bit limited at the moment...

The main issue is fixing the special issue bug. Then we can fix the docker stuff again.

But feel free to fork and make a PR with wherever you think is helpful. Thanks a lot

**Comment by joergi** [comment]
blocked by #89
