### ISSUE TITLE
making the shell scripts usable for windows powershell

### ISSUE THREAD

**Issue by joergi** [joergi/MagPiDownloader#3]
At this time, the scripts are only working on Linux and OSX machines.

With Windows 8 and 10, Microsoft has introduced the Powershell.

So there is a good opportunity to bring the MagPiDownloader to the Windows system too.

I started to do this by myself, but it was not that easy.
I found on StackOverflow, that it should work like this:

```
$client = new-object System.Net.WebClient
$client.DownloadFile("https://www.raspberrypi.org/magpi-issues/Essentials_Games_v1.pdf","special_issues/")

```
But maybe there was something wrong, or I started it wrong.

That's why I ask here for help.  
Thanks a lot.

**Comment by Rubemlrm** [comment]
I think that i can help you doing that.during the weekend i will try handle this issue

**Comment by joergi** [comment]
would be lovely! should I assign it to you?

**Comment by rdtheriault** [comment]
You just need to specify the path better. This worked for me

```
$client = new-object System.Net.WebClient
$client.DownloadFile("https://www.raspberrypi.org/magpi-issues/MagPi62.pdf","C:/users/test.pdf")
```

**Comment by joergi** [comment]
is there one way to use a relative path @rdtheriault ?

**Comment by rdtheriault** [comment]
Yes, you could do something like this to the user folder 

`$client.DownloadFile("https://www.raspberrypi.org/magpi-issues/MagPi62.pdf","$env:USERPROFILE/test.pdf")`

**Comment by joergi** [comment]
ok, I tested it yesterday, but my shell was restricted. So first I have to find out, how to unlock it.
... I know why I switched more than 15 years ago to Linux

**Comment by Rubemlrm** [comment]
restricted how  ? what error did you get .

Btw you can assign this to me if you want.

**Comment by joergi** [comment]
I know that I can make the language as a parameter. But I want to keep it as simple as possible for all the languages, that's why I have separated files.

Can you try to assign by yourself? Looks like, I can't do this. thanks

That's what I got in my Powershell
![mmolfpfeljhgcjem](https://user-images.githubusercontent.com/1439809/31014696-987d1598-a51c-11e7-9e93-76b3bcd08077.png)
code in the file looks like this:

> $client = new-object System.Net.WebClient
> $client.DownloadFile("https://www.raspberrypi.org/magpi-issues/MagPi62.pdf","C:\Users\test.pdf")

(i also tried it yesterday night with path to `C:/Users/test.pdf` )

**Comment by Rubemlrm** [comment]
To fix that error:

Start Windows PowerShell with the "Run as Administrator" option. Only members of the Administrators group on the computer can change the execution policy.
Enable running unsigned scripts by entering:
set-executionpolicy remotesigned

**Comment by joergi** [comment]
Now the assignment works.
I will not be able to have a look before Wednesday to it.
But thanks a lot for helping 👍

**Comment by joergi** [comment]
Great, looking forward for it.

**Comment by joergi** [comment]
By the way, this issue is part of the https://hacktoberfest.digitalocean.com so be sure  to have a look to it - maybe you will get a free shirt!

**Comment by joergi** [comment]
perfect job done by @Rubemlrm !!!
Thanks a lot for the work man!

**Comment by Rubemlrm** [comment]
this issue is relative to #5
