### ISSUE TITLE
add Windows testing to travis-ci.yml

### ISSUE THREAD

**Issue by joergi** [joergi/MagPiDownloader#8]
The Windows Powershell scripts needs to be tested with travis too.

**Comment by VerteDinde** [comment]
Hey @joergi, I don't know if Travis actually supports Windows testing. It looks like they might not: https://docs.travis-ci.com/user/multi-os/

Have you looked into AppVeyor at all? They can do free Windows CI/CD for open source projects and they also support Cygwin, so you could run your scripts by writing `sh magpi-special-issue-downloader.sh`, for example.

**Comment by joergi** [comment]
Thanks @VerteDinde - I 'll give it a try on the weekend

**Comment by Rubemlrm** [comment]
@joergi any luck with the tests ?

**Comment by joergi** [comment]
no time yet :-1: 
If you just want to use your docker images, just go for it! :1st_place_medal:

**Comment by Rubemlrm** [comment]
i will try that later =) to see if all goes fine

**Comment by joergi** [comment]
I assigned you too.
Too busy at the moment 😒

**Comment by joergi** [comment]
Thanks a lot again.
Again GREAT JOB 🏆🎖️
