### ISSUE TITLE
fix regular issues on powershell

### ISSUE THREAD

**Issue by joergi** [joergi/MagPiDownloader#83]
at the moment there is an error in the testing (also in the running?) of the download of the regular issues on Windows Powershell

as I'm not having a Windows machine to really debug it locally.....

Test with errors:  https://github.com/joergi/MagPiDownloader/actions/runs/3253313845/jobs/5340465575

**Comment by joergi** [comment]
To reactivate testing please bring in the commented part [here (L16-L55](https://github.com/joergi/MagPiDownloader/blob/main/.github/workflows/testing-regular-issues.yml#L16)

**Comment by Jaykul** [comment]
Have you tried it on powershell on linux?

**Comment by joergi** [comment]
> Have you tried it on powershell on linux?

I had no idea, there is powershell on Linux, to be honest.
